### ISSUE TITLE
Fails for DataSet 4535

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3oml#1]
https://www.openml.org/d/4535

```r
library(mlr3)
library(mlr3oml)
task = tsk("oml", data_id = 4535)
```

```
Error in switch(self$features[.(target), data_type], nominal = TaskClassif$new(self$name,  : 
  EXPR must be a length 1 vector
Error during wrapup: 'length(x) = 13 > 1' in coercion to 'logical(1)'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

**Comment by mllg** [comment]
There is no default target column in the data set. Should be an error while converting to a task.

**Comment by mllg** [comment]
t = OMLTask$new(146805)$task works ... I guess we need 2 things:

1) An error message if there is no target column, and
2) A way to choose a column as target.
