### ISSUE TITLE
server responses should be cached as-is

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3oml#50]

**Comment by mllg** [comment]
Currently we do some conversions for json and actually change the server response before caching. I would argue that this is fine for (small) json responses, but not for larger records that are usually already stored on disk. However, this needs to be carefully re-evaluated.

**Comment by sebffischer** [comment]
For the arff files we actually modify the names using `make.names()` (see `read_arff()`).

**Comment by sebffischer** [comment]
it is ok as it is
