### ISSUE TITLE
Support sparseARFF

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr3oml#6]
mlr3oml currently does only support ARFF format. However, OpenML has lot of data stored as sparseARFF. Although RWeka is a bad dependency, it has an arff.reader that is able to import this format, e.g.:

```r
library(OpenML)
setOMLConfig(arff.reader = "RWeka")
d = as.data.table(getOMLDataSet(292))
```

It is a bit annoying to write an own function that supports to import sparseARFF files but I think it would be nice to be able to import also sparseARFF files.

**Comment by mllg** [comment]
Added an automatic fallback in 91ecc52f9c9c937238e30082c49209fb50b1d994.
